const NAMES = [
{ id:1, arabic:"ٱلرَّحْمَـٰنُ", translit:"Ar-Rahman", meaning:"Le Tout Miséricordieux" },
{ id:2, arabic:"ٱلرَّحِيمُ", translit:"Ar-Rahim", meaning:"Le Très Miséricordieux" },
{ id:3, arabic:"ٱلْمَلِكُ", translit:"Al-Malik", meaning:"Le Souverain" },
{ id:4, arabic:"ٱلْقُدُّوسُ", translit:"Al-Quddus", meaning:"Le Très Saint" },
{ id:5, arabic:"ٱلسَّلَامُ", translit:"As-Salam", meaning:"La Paix" },
{ id:6, arabic:"ٱلْمُؤْمِنُ", translit:"Al-Mu’min", meaning:"Le Rassurant" },
{ id:7, arabic:"ٱلْمُهَيْمِنُ", translit:"Al-Muhaymin", meaning:"Le Protecteur" },
{ id:8, arabic:"ٱلْعَزِيزُ", translit:"Al-‘Aziz", meaning:"Le Tout Puissant" },
{ id:9, arabic:"ٱلْجَبَّارُ", translit:"Al-Jabbar", meaning:"Le Contraignant" },
{ id:10, arabic:"ٱلْمُتَكَبِّرُ", translit:"Al-Mutakabbir", meaning:"Le Superbe" },
{ id:11, arabic:"ٱلْخَالِقُ", translit:"Al-Khaliq", meaning:"Le Créateur" },
{ id:12, arabic:"ٱلْبَارِئُ", translit:"Al-Bari", meaning:"Le Producteur" },
{ id:13, arabic:"ٱلْمُصَوِّرُ", translit:"Al-Musawwir", meaning:"Le Formateur" },
{ id:14, arabic:"ٱلْغَفَّارُ", translit:"Al-Ghaffar", meaning:"Le Grand Pardonneur" },
{ id:15, arabic:"ٱلْقَهَّارُ", translit:"Al-Qahhar", meaning:"Le Dominateur" },
{ id:16, arabic:"ٱلْوَهَّابُ", translit:"Al-Wahhab", meaning:"Le Donateur" },
{ id:17, arabic:"ٱلرَّزَّاقُ", translit:"Ar-Razzaq", meaning:"Le Pourvoyeur" },
{ id:18, arabic:"ٱلْفَتَّاحُ", translit:"Al-Fattah", meaning:"L’Ouverture" },
{ id:19, arabic:"ٱلْعَلِيمُ", translit:"Al-‘Alim", meaning:"L’Omniscient" },
{ id:20, arabic:"ٱلْقَابِضُ", translit:"Al-Qabid", meaning:"Celui qui restreint" },
{ id:21, arabic:"ٱلْبَاسِطُ", translit:"Al-Basit", meaning:"Celui qui étend" },
{ id:22, arabic:"ٱلْخَافِضُ", translit:"Al-Khafid", meaning:"Celui qui abaisse" },
{ id:23, arabic:"ٱلرَّافِعُ", translit:"Ar-Rafi‘", meaning:"Celui qui élève" },
{ id:24, arabic:"ٱلْمُعِزُّ", translit:"Al-Mu‘izz", meaning:"Celui qui honore" },
{ id:25, arabic:"ٱلْمُذِلُّ", translit:"Al-Mudhill", meaning:"Celui qui humilie" },
{ id:26, arabic:"ٱلسَّمِيعُ", translit:"As-Sami‘", meaning:"L’Audient" },
{ id:27, arabic:"ٱلْبَصِيرُ", translit:"Al-Basir", meaning:"Le Clairvoyant" },
{ id:28, arabic:"ٱلْحَكَمُ", translit:"Al-Hakam", meaning:"Le Juge" },
{ id:29, arabic:"ٱلْعَدْلُ", translit:"Al-‘Adl", meaning:"Le Juste" },
{ id:30, arabic:"ٱللَّطِيفُ", translit:"Al-Latif", meaning:"Le Subtil" },
{ id:31, arabic:"ٱلْخَبِيرُ", translit:"Al-Khabir", meaning:"Le Bien Informé" },
{ id:32, arabic:"ٱلْحَلِيمُ", translit:"Al-Halim", meaning:"Le Longanime" },
{ id:33, arabic:"ٱلْعَظِيمُ", translit:"Al-‘Azim", meaning:"L’Immense" },
{ id:34, arabic:"ٱلْغَفُورُ", translit:"Al-Ghafur", meaning:"Le Pardonneur" },
{ id:35, arabic:"ٱلشَّكُورُ", translit:"Ash-Shakur", meaning:"Le Reconnaissant" },
{ id:36, arabic:"ٱلْعَلِيُّ", translit:"Al-‘Aliyy", meaning:"Le Très Haut" },
{ id:37, arabic:"ٱلْكَبِيرُ", translit:"Al-Kabir", meaning:"Le Grand" },
{ id:38, arabic:"ٱلْحَفِيظُ", translit:"Al-Hafiz", meaning:"Le Préservateur" },
{ id:39, arabic:"ٱلْمُقِيتُ", translit:"Al-Muqit", meaning:"Le Nourricier" },
{ id:40, arabic:"ٱلْحَسِيبُ", translit:"Al-Hasib", meaning:"Celui qui tient compte" },
{ id:41, arabic:"ٱلْجَلِيلُ", translit:"Al-Jalil", meaning:"Le Majestueux" },
{ id:42, arabic:"ٱلْكَرِيمُ", translit:"Al-Karim", meaning:"Le Généreux" },
{ id:43, arabic:"ٱلرَّقِيبُ", translit:"Ar-Raqib", meaning:"Le Vigilant" },
{ id:44, arabic:"ٱلْمُجِيبُ", translit:"Al-Mujib", meaning:"L’Exauceur" },
{ id:45, arabic:"ٱلْوَاسِعُ", translit:"Al-Wasi‘", meaning:"L’Immense" },
{ id:46, arabic:"ٱلْحَكِيمُ", translit:"Al-Hakim", meaning:"Le Sage" },
{ id:47, arabic:"ٱلْوَدُودُ", translit:"Al-Wadud", meaning:"Le Bien Aimant" },
{ id:48, arabic:"ٱلْمَجِيدُ", translit:"Al-Majid", meaning:"Le Glorieux" },
{ id:49, arabic:"ٱلْبَاعِثُ", translit:"Al-Ba‘ith", meaning:"Le Ressusciteur" },
{ id:50, arabic:"ٱلشَّهِيدُ", translit:"Ash-Shahid", meaning:"Le Témoin" },
{ id:51, arabic:"ٱلْحَقُّ", translit:"Al-Haqq", meaning:"La Vérité" },
{ id:52, arabic:"ٱلْوَكِيلُ", translit:"Al-Wakil", meaning:"Le Garant" },
{ id:53, arabic:"ٱلْقَوِيُّ", translit:"Al-Qawiyy", meaning:"Le Fort" },
{ id:54, arabic:"ٱلْمَتِينُ", translit:"Al-Matin", meaning:"Le Ferme" },
{ id:55, arabic:"ٱلْوَلِيُّ", translit:"Al-Waliyy", meaning:"Le Protecteur proche" },
{ id:56, arabic:"ٱلْحَمِيدُ", translit:"Al-Hamid", meaning:"Le Digne de louange" },
{ id:57, arabic:"ٱلْمُحْصِي", translit:"Al-Muhsi", meaning:"Celui qui dénombre" },
{ id:58, arabic:"ٱلْمُبْدِئُ", translit:"Al-Mubdi", meaning:"Le Commenceur" },
{ id:59, arabic:"ٱلْمُعِيدُ", translit:"Al-Mu‘id", meaning:"Le Répétiteur" },
{ id:60, arabic:"ٱلْمُحْيِي", translit:"Al-Muhyi", meaning:"Le Donneur de vie" },
{ id:61, arabic:"ٱلْمُمِيتُ", translit:"Al-Mumit", meaning:"Le Donneur de mort" },
{ id:62, arabic:"ٱلْحَيُّ", translit:"Al-Hayy", meaning:"Le Vivant" },
{ id:63, arabic:"ٱلْقَيُّومُ", translit:"Al-Qayyum", meaning:"Le Subsistant" },
{ id:64, arabic:"ٱلْوَاجِدُ", translit:"Al-Wajid", meaning:"Celui qui trouve" },
{ id:65, arabic:"ٱلْمَاجِدُ", translit:"Al-Majid", meaning:"Le Noble" },
{ id:66, arabic:"ٱلْوَاحِدُ", translit:"Al-Wahid", meaning:"L’Unique" },
{ id:67, arabic:"ٱلْأَحَدُ", translit:"Al-Ahad", meaning:"L’Un" },
{ id:68, arabic:"ٱلصَّمَدُ", translit:"As-Samad", meaning:"Le Soutien absolu" },
{ id:69, arabic:"ٱلْقَادِرُ", translit:"Al-Qadir", meaning:"Le Puissant" },
{ id:70, arabic:"ٱلْمُقْتَدِرُ", translit:"Al-Muqtadir", meaning:"Le Très Puissant" },
{ id:71, arabic:"ٱلْمُقَدِّمُ", translit:"Al-Muqaddim", meaning:"Celui qui avance" },
{ id:72, arabic:"ٱلْمُؤَخِّرُ", translit:"Al-Mu’akhkhir", meaning:"Celui qui retarde" },
{ id:73, arabic:"ٱلْأَوَّلُ", translit:"Al-Awwal", meaning:"Le Premier" },
{ id:74, arabic:"ٱلْآخِرُ", translit:"Al-Akhir", meaning:"Le Dernier" },
{ id:75, arabic:"ٱلظَّاهِرُ", translit:"Az-Zahir", meaning:"L’Apparent" },
{ id:76, arabic:"ٱلْبَاطِنُ", translit:"Al-Batin", meaning:"Le Caché" },
{ id:77, arabic:"ٱلْوَالِي", translit:"Al-Wali", meaning:"Le Gouverneur" },
{ id:78, arabic:"ٱلْمُتَعَالِي", translit:"Al-Muta‘ali", meaning:"Le Très Élevé" },
{ id:79, arabic:"ٱلْبَرُّ", translit:"Al-Barr", meaning:"Le Bon" },
{ id:80, arabic:"ٱلتَّوَّابُ", translit:"At-Tawwab", meaning:"Celui qui accepte le repentir" },
{ id:81, arabic:"ٱلْمُنْتَقِمُ", translit:"Al-Muntaqim", meaning:"Le Vengeur" },
{ id:82, arabic:"ٱلْعَفُوُّ", translit:"Al-‘Afuww", meaning:"L’Indulgent" },
{ id:83, arabic:"ٱلرَّؤُوفُ", translit:"Ar-Ra’uf", meaning:"Le Très Compatissant" },
{ id:84, arabic:"مَالِكُ ٱلْمُلْكُ", translit:"Malik al-Mulk", meaning:"Maître de la Royauté" },
{ id:85, arabic:"ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ", translit:"Dhul-Jalali wal-Ikram", meaning:"Plein de Majesté et de Générosité" },
{ id:86, arabic:"ٱلْمُقْسِطُ", translit:"Al-Muqsit", meaning:"L’Équitable" },
{ id:87, arabic:"ٱلْجَامِعُ", translit:"Al-Jami‘", meaning:"Le Rassembleur" },
{ id:88, arabic:"ٱلْغَنِيُّ", translit:"Al-Ghaniyy", meaning:"Le Suffisant" },
{ id:89, arabic:"ٱلْمُغْنِيُّ", translit:"Al-Mughni", meaning:"Celui qui enrichit" },
{ id:90, arabic:"ٱلْمَانِعُ", translit:"Al-Mani‘", meaning:"Celui qui empêche" },
{ id:91, arabic:"ٱلضَّارُ", translit:"Ad-Darr", meaning:"Celui qui nuit" },
{ id:92, arabic:"ٱلنَّافِعُ", translit:"An-Nafi‘", meaning:"Celui qui profite" },
{ id:93, arabic:"ٱلنُّورُ", translit:"An-Nur", meaning:"La Lumière" },
{ id:94, arabic:"ٱلْهَادِي", translit:"Al-Hadi", meaning:"Le Guide" },
{ id:95, arabic:"ٱلْبَدِيعُ", translit:"Al-Badi‘", meaning:"L’Incomparable" },
{ id:96, arabic:"ٱلْبَاقِي", translit:"Al-Baqi", meaning:"L’Éternel" },
{ id:97, arabic:"ٱلْوَارِثُ", translit:"Al-Warith", meaning:"L’Héritier" },
{ id:98, arabic:"ٱلرَّشِيدُ", translit:"Ar-Rashid", meaning:"Le Guide droit" },
{ id:99, arabic:"ٱلصَّبُورُ", translit:"As-Sabur", meaning:"Le Patient" }
];
